<li class="col-4-1 not-animated" data-animate="fadeInUp" data-delay="200" style="">
                        <div class="portfolio-img"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="" /></a></div>
                        <div class="portfolio-title">
                          <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                        </div>
                      </li>