<li class="headlines-content">
                                    <div class="entry-item">
                                      <div class="typo">
                                        <div class="typo-img">
                                          <div class="entry-img"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="160" alt="[field:title/]" /></a></div>
                                        </div>
                                        <div class="typo-text">
                                          <div class="entry-title">
                                            <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                                          </div>
                                          <div class="entry-summary">
                                            <div class="qhd-content">
                                              <p>[field:description function='cn_substr(@me,250)'/]...</p>
                                            </div>
                                          </div>
                                        </div>
                                        </div>
                                    </div>
                                    </li>