<?php
$z[0]=Array("global","",704,725);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",1143,1234);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n            <li {dede:field name='currentstyle'/}><a class=\"first-level\" href=\"{dede:field name='typeurl'/}\" target=\"\"><strong>{dede:field name='typename'/}</strong></a><i></i>\r\n              <ul class=\"\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li class=\"\"><a class=\"\" href=\"[field:typelink/]\" target=\"\"><strong>[field:typename/]</strong></a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",1330,1864);
$z[2][4]['row']="10";
$z[2][4]['typeid']="top";
$z[3]=Array("channelartlist","\r\n          <li><span><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></span><a href=\"javascript:;\"><i class=\"touch-arrow-down\"></i></a>\r\n            <ul>\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",2798,3259);
$z[3][4]['row']="10";
$z[3][4]['typeid']="top";

?>